plot_variance = @(x,lower,upper,color) set(fill([x,x(end:-1:1)],[upper, ...
                    lower(end:-1:1)],color),'EdgeColor',color);

x = num_training_patches*15;
x_auto = num_training_patches_used{2};
plot_perf = vertcat(all_perf{2}(:,num_training_patches), all_perf{3}(:, ...
                                                  num_training_patches), ...
                    all_perf{6}(:,num_training_patches))
plot_perf_x = vertcat(repmat(x_auto,4,1),repmat(x,8,1))
%plot(plot_perf_x', plot_perf');

figure
hold on
plot_variance(x_auto, all_perf{2}(2,num_training_patches), all_perf{2}(3, ...
                                                  num_training_patches), ...
              [0.9 0.9 0])
plot_variance(x_auto, all_perf{2}(2,num_training_patches), ...
                  all_perf{2}(1,num_training_patches), [0.9 0.9 0])
plot_variance(x_auto, all_perf{2}(2,num_training_patches), ...
                  all_perf{2}(2,num_training_patches), [0.9 0.9 0])
plot_variance(x, all_perf{6}(2,num_training_patches), all_perf{6}(3, ...
                                                  num_training_patches), ...
                  [0 0.9 0.9])
plot_variance(x, all_perf{6}(2,num_training_patches), all_perf{6}(1, ...
                                                  num_training_patches), ...
                  [0 0.9 0.9])
plot_variance(x, all_perf{6}(2,num_training_patches), all_perf{6}(4, ...
                                                  num_training_patches), ...
                  [0 0.9 0.9])
plot_variance(x, all_perf{3}(2,num_training_patches), all_perf{3}(4, ...
                                                  num_training_patches), ...
                  [0.9 0 0.9])
plot_variance(x, all_perf{3}(2,num_training_patches), all_perf{3}(3, ...
                                                  num_training_patches), ...
                  [0.9 0 0.9])
plot_variance(x, all_perf{3}(2,num_training_patches), all_perf{3}(1, ...
                                                  num_training_patches), ...
                  [0.9 0 0.9])
grid on
set(gca, 'XTick' [0:100:1500])
figure
hold on
p1 = plot(x_auto,all_perf{2}(4,num_training_patches),'-gs','LineWidth',2)
p2 = plot(x,all_perf{3}(2,num_training_patches),'-md','LineWidth',2)
p3 = plot(x,all_perf{6}(2,num_training_patches),'-c*','LineWidth',2)
grid on
set(gca, 'XTick', [0:150:1500])
legend('Linear Auto Patch, L1 SVM','Linear Human Patch, Chi^{2} SVM', ...
       'Sigmoid Human Patch, Chi^{2} SVM')
ylabel('Scene Classification Accuracy (%)', 'FontSize', 14)
xlabel('Number of Discriminitive Patches', 'FontSize', 14)